on: [push]

jobs:
  build:
    name: Build and push to gh-pages 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running build.sh script
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        sh build.sh
  
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
