on: [push]

jobs:
  build:
    name: Build and push into gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running build_and_push.sh script
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        sh build_and_push.sh
