on: [push]

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running build_and_push.sh script
      run: |
        sh build_and_push.sh
