on: [push]

jobs:
  build:
    name: Build and push to gh-pages 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running build logic
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git submodule update --init --recursive
        git submodule update --recursive --remote
        yarn install
        yarn run build
        git rm -r build/client-protocol
        rm -rf .git/modules/build/client-protocol
        rm -rf build/client-protocol
        cp -r public/client-protocol/ build/
        rm -r build/client-protocol/.git
        git add .
        git commit -m "Built Page"
        git push
 #       sh build.sh
  
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
